# Generated by Django 3.1.3 on 2020-11-19 18:23

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Заголовок', max_length=255, verbose_name='Заголовок')),
                ('file', models.FileField(default=None, null=True, upload_to=news.models.get_file_path, verbose_name='Файл')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
        ),
    ]
