# Generated by Django 3.1.3 on 2020-11-17 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('TO', 'SENT'), ('FROM', 'RECEIVED')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot.telegramuser')),
            ],
        ),
    ]
