# Generated by Django 3.1.3 on 2020-11-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('SENT', 'SENT'), ('RECEIVED', 'RECEIVED')], max_length=10),
        ),
    ]
