# Generated by Django 3.1.3 on 2020-11-12 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField(unique=True, verbose_name='Код чата')),
                ('name', models.CharField(default='Друг', max_length=255, verbose_name='Псевдоним')),
                ('active_psy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_students', to=settings.AUTH_USER_MODEL, verbose_name='Текущий психолог')),
                ('main_psy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_students', to=settings.AUTH_USER_MODEL, verbose_name='Основной психолог')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
