# Generated by Django 3.1.3 on 2020-11-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField(unique=True, verbose_name='Код чата')),
                ('state', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
            ],
        ),
    ]
