# Generated by Django 3.1.3 on 2020-11-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_chatstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_poor',
            field=models.BooleanField(default=False),
        ),
    ]
